### ISSUE TITLE
more documentation on the new cli tool's options

### ISSUE THREAD

**Issue by Ali-Flt** [VQEG/siti-tools#15]
The new SITI cli in main branch has many new features and input parameters with little description. Could you elaborate more on the newly added options and how they should be extracted from the input video sequence (to be given as input to siti-tools)?
Any references, documentation or sources would be helpful.

Also I believe the documentation link on the legacy branch ([https://telecommunication-telemedia-assessment.github.io/siti-tools/](https://telecommunication-telemedia-assessment.github.io/siti-tools/)) is not working.

Thanks,
Ali

**Comment by slhck** [comment]
Thanks for the comment. We are currently preparing everything to be more officially released, so the changes you are seeing are definitely not documented in the way that makes it easy to use. Note though that most of these options are optional, meaning that you can run the tool with a “good old” video source as you would have run a previous version.

I will fix the legacy branch link. Thanks for pointing that out.

**Comment by Ali-Flt** [comment]
Thanks for your answer. I actually was wondering whether I even need to set the options or the default values will do the job (specially for SDR videos). That answers it then. 
Thanks again

**Comment by slhck** [comment]
I slightly updated the README to cover more use cases and structure the documentation a bit.
